### PR TITLE
https://luceeserver.atlassian.net/browse/LDEV-370

### PR DESCRIPTION
**Pull request by clitnak**
https://luceeserver.atlassian.net/browse/LDEV-370

### CODE REVIEW

**Comment by michaeloffner** [comment]
it would be great if you could document ths in the wiki

**Comment by michaeloffner** [comment]
adapted for Lucee 5:
https://github.com/lucee/Lucee/commit/2d30fc68caa1776717b35dc02e7bf003a5d671b2

**Comment by clitnak** [comment]
The wiki on bitbucket that is referenced from the lucee4 github homepage?

**Comment by andrew-dixon** [comment]
The wiki on BitBucket is in the process of being moved to the official docs (http://docs.lucee.org) so for the moment please hold fire on this as we have already copied everything out of the wiki.

**Comment by clitnak** [comment]
Cool. Let me know when I can. I checked out http://docs.lucee.org and I at a cursory glance, I couldn't find a good place to add this info. It doesn't fall in the categories of tags or functions.

**Pull request merged**
