### PR TITLE
LDEV-490 only try and persist to ORM if ORM is enabled

### PR DESCRIPTION
**Pull request by SimonHooker**

### CODE REVIEW

**Comment by CarsonBytes** [comment]
Hello Simon, How much time is needed to fix this bug and make a release?

**Comment by SimonHooker** [comment]
Hi @carsonng  sorry for late response - I've already got a fix submitted but it's awaiting QA - will ask @michaeloffner  to take a look

**Comment by CarsonBytes** [comment]
@SimonHooker  @michaeloffner 
thanks! any updates so far when to release?

**Comment by micstriit** [comment]
could you adapt the same change for the Lucee 5 hibernate extension?

**Pull request merged**
